### ISSUE TITLE
load_mocat_sample fails when given file names with multiple pair identifiers

### ISSUE THREAD

**Issue by jakob-wirbel** [ngless-toolkit/ngless#127]
I got an error message when i tried to run it on some files that have a big of an unconventional name.
The files are named, for example:

```bash
SAMEA3136648.pair.1.ERR688506_1.fastq.gz
SAMEA3136648.pair.2.ERR688506_2.fastq.gz
SAMEA3136648.single.ERR688506.fastq.gz
```
When i run `NGless`, it throws the following error:
```bash
Exiting after fatal error while loading and running script
Data Error (the input data did not conform to ngless' expectations)
Cannot find match for file: [...]/SAMEA3136648.pair.1.ERR688506_1.fastq.gz
```

However, when I re-name the files to:
```bash
SAMEA3136648.pair.1.fastq.gz
SAMEA3136648.pair.2.fastq.gz
SAMEA3136648.single.fastq.gz
```
the script runs without a problem.

My question would be if that behaviour is a bug or if it should behave this way?

**Comment by unode** [comment]
This is a confusing situation but it's working as designed, i.e. not a bug.
The confusion originates from two sets of identifiers changing in the filename.
The expectation is that only the end of the filename changes, otherwise the files are considered two independent samples.

In the above example you'd need:
```
SAMEA3136648.pair.1.ERR688506_[12].fastq.gz
```
and therefore:
```
SAMEA3136648.pair.1.ERR688506_1.fastq.gz
SAMEA3136648.pair.1.ERR688506_2.fastq.gz
```

but since the `pair.X` part also changes to `pair.2`, the files don't match anymore.

Similarly:
```
SAMEA3136648.pair.1.ERR688506_1.fastq.gz
SAMEA3136648.pair.2.ERR688506_1.fastq.gz
```
would be treated as two independent samples.

In addition since NGLess detects the presence of the `_1` suffix it expects to find a matching pair.
Since it doesn't, it errors on the side of caution.

**Comment by jakob-wirbel** [comment]
Ah okay, thanks for pointing that out!

And i totally agree, it is a confusing situation, but it is better to have an error on the side of caution...
